basePath: /api
host: localhost:4000
info:
  contact: {}
  description: Go Boiler plate to start with go and gingonic
  title: Go-boiler service
  version: "1.0"
paths:
  /api/GetVal:
    get:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: List accounts
      tags:
      - accounts
  /api/addVals:
    post:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Add Values
      tags:
      - accounts
swagger: "2.0"
